server:
  port: 8081
  servlet:
    context-path: /luckymoney

limit:
  minMoney: 1
  maxMoney: 999
  description: The min LuckyMoney should be ${limit.minMoney} $, the max should be ${limit.maxMoney} $!