server:
  port: 8081
  servlet:
    context-path: /luckymoney

limit:
  minMoney: 0.01
  maxMoney: 999
  description: The min LuckyMoney should be ${limit.minMoney} $, the max should be ${limit.maxMoney} $!

Spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: woaini1314
    url: jdbc:mysql://127.0.0.1:3306/luckymoney?serverTimezone=America/Los_Angeles
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true